<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="javaPackage" nsURI="https://www.example.org/java" nsPrefix="java">
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eAnnotations source="Override"/>
    <eAnnotations source="Override"/>
    <eAnnotations source="SuppressWarnings"/>
    <eAnnotations source="Override"/>
    <eAnnotations source="Override"/>
    <eAnnotations source="Override"/>
    <eOperations name="eStaticClass">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="getIn">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="getOut">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="eGet">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eParameters name="featureID">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
      <eParameters name="resolve">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
      <eParameters name="coreType">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
    </eOperations>
    <eOperations name="eSet">
      <eParameters name="featureID">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
      <eParameters name="newValue">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
    </eOperations>
    <eOperations name="eUnset">
      <eParameters name="featureID">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
    </eOperations>
    <eOperations name="eIsSet">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eParameters name="featureID">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PetriAdapterFactory">
    <eAnnotations source="Override"/>
    <eAnnotations source="Override"/>
    <eOperations name="isFactoryForType">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eParameters name="object">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
    </eOperations>
    <eOperations name="createAdapter">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eParameters name="target">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
    </eOperations>
    <eOperations name="createPetriNetAdapter">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="createNamedElementAdapter">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="createPlaceAdapter">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="createTransitionAdapter">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="createEObjectAdapter">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PetriSwitch">
    <eAnnotations source="Override"/>
    <eAnnotations source="Override"/>
    <eAnnotations source="Override"/>
    <eOperations name="isSwitchFor">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eParameters name="ePackage">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
    </eOperations>
    <eOperations name="doSwitch">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eParameters name="classifierID">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
      <eParameters name="theEObject">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
    </eOperations>
    <eOperations name="casePetriNet">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eParameters name="object">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
    </eOperations>
    <eOperations name="caseNamedElement">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eParameters name="object">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
    </eOperations>
    <eOperations name="casePlace">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eParameters name="object">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
    </eOperations>
    <eOperations name="caseTransition">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eParameters name="object">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
    </eOperations>
    <eOperations name="defaultCase">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eParameters name="object">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Place">
    <eAnnotations source="Override"/>
    <eAnnotations source="Override"/>
    <eAnnotations source="Override"/>
    <eAnnotations source="Override"/>
    <eAnnotations source="Override"/>
    <eAnnotations source="Override"/>
    <eOperations name="eStaticClass">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="getTokens">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="setTokens">
      <eParameters name="newTokens">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
    </eOperations>
    <eOperations name="eGet">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eParameters name="featureID">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
      <eParameters name="resolve">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
      <eParameters name="coreType">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
    </eOperations>
    <eOperations name="eSet">
      <eParameters name="featureID">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
      <eParameters name="newValue">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
    </eOperations>
    <eOperations name="eUnset">
      <eParameters name="featureID">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
    </eOperations>
    <eOperations name="eIsSet">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eParameters name="featureID">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
    </eOperations>
    <eOperations name="toString">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TOKENS_EDEFAULT">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tokens">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PetriNet">
    <eAnnotations source="Override"/>
    <eAnnotations source="Override"/>
    <eAnnotations source="Override"/>
    <eAnnotations source="SuppressWarnings"/>
    <eAnnotations source="Override"/>
    <eAnnotations source="Override"/>
    <eAnnotations source="Override"/>
    <eOperations name="eStaticClass">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="getElems">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="eInverseRemove">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eParameters name="otherEnd">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
      <eParameters name="featureID">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
      <eParameters name="msgs">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
    </eOperations>
    <eOperations name="eGet">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eParameters name="featureID">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
      <eParameters name="resolve">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
      <eParameters name="coreType">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
    </eOperations>
    <eOperations name="eSet">
      <eParameters name="featureID">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
      <eParameters name="newValue">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
    </eOperations>
    <eOperations name="eUnset">
      <eParameters name="featureID">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
    </eOperations>
    <eOperations name="eIsSet">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eParameters name="featureID">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement">
    <eAnnotations source="Override"/>
    <eAnnotations source="Override"/>
    <eAnnotations source="Override"/>
    <eAnnotations source="Override"/>
    <eAnnotations source="Override"/>
    <eAnnotations source="Override"/>
    <eOperations name="eStaticClass">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="getName">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="setName">
      <eParameters name="newName">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eParameters>
    </eOperations>
    <eOperations name="eGet">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eParameters name="featureID">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
      <eParameters name="resolve">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
      <eParameters name="coreType">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
    </eOperations>
    <eOperations name="eSet">
      <eParameters name="featureID">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
      <eParameters name="newValue">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
    </eOperations>
    <eOperations name="eUnset">
      <eParameters name="featureID">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
    </eOperations>
    <eOperations name="eIsSet">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eParameters name="featureID">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
    </eOperations>
    <eOperations name="toString">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NAME_EDEFAULT">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PetriFactory">
    <eAnnotations source="Override"/>
    <eAnnotations source="Deprecated"/>
    <eOperations name="init">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="create">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eParameters name="eClass">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
    </eOperations>
    <eOperations name="createPetriNet">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="createPlace">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="createTransition">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="getPetriPackage">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="getPackage">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eINSTANCE" upperBound="-1" eType="//PetriFactory" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PetriPackage">
    <eOperations name="init">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="getPetriNet">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="getPetriNet_Elems">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="getNamedElement">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="getNamedElement_Name">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="getPlace">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="getPlace_Tokens">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="getTransition">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="getTransition_In">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="getTransition_Out">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="getPetriFactory">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="createPackageContents"/>
    <eOperations name="initializePackageContents"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eNAME">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eNS_URI">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eNS_PREFIX">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PETRI_NET">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PETRI_NET__ELEMS">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PETRI_NET_FEATURE_COUNT">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NAMED_ELEMENT">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NAMED_ELEMENT__NAME">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NAMED_ELEMENT_FEATURE_COUNT">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PLACE">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PLACE__NAME">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PLACE__TOKENS">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PLACE_FEATURE_COUNT">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TRANSITION">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TRANSITION__NAME">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TRANSITION__IN">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TRANSITION__OUT">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TRANSITION_FEATURE_COUNT">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isInited">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isCreated">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isInitialized">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eINSTANCE" upperBound="-1" eType="//PetriPackage" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Literals" abstract="true" interface="true"/>
</ecore:EPackage>
